In [3]:
import pandas as pd

In [4]:
import os
os.listdir("Dataset")

['.ipynb_checkpoints',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_reviews_dataset.csv']

In [11]:
orders=pd.read_csv("Dataset/olist_orders_dataset.csv")

In [12]:
orders.shape

(99441, 8)

In [13]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [16]:
orders.head(50)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04 00:00:00
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06 00:00:00
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29 00:00:00
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23 00:00:00
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28 00:00:00
21,f848643eec1d69395095eb3840d2051e,4fa1cd166fa598be6de80fa84eaade43,delivered,2018-03-15 08:52:40,2018-03-15 09:09:31,2018-03-15 19:52:48,2018-03-19 18:08:32,2018-03-29 00:00:00
22,2807d0e504d6d4894d41672727bc139f,72ae281627a6102d9b3718528b420f8a,delivered,2018-02-03 20:37:35,2018-02-03 20:50:22,2018-02-05 22:37:28,2018-02-08 16:13:46,2018-02-21 00:00:00
23,95266dbfb7e20354baba07964dac78d5,a166da34890074091a942054b36e4265,delivered,2018-01-08 07:55:29,2018-01-08 08:07:31,2018-01-24 23:16:37,2018-01-26 17:32:38,2018-02-21 00:00:00
24,f3e7c359154d965827355f39d6b1fdac,62b423aab58096ca514ba6aa06be2f98,delivered,2018-08-09 11:44:40,2018-08-10 03:24:51,2018-08-10 12:29:00,2018-08-13 18:24:27,2018-08-17 00:00:00
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12 00:00:00
26,acce194856392f074dbf9dada14d8d82,7e20bf5ca92da68200643bda76c504c6,delivered,2018-06-04 00:00:13,2018-06-05 00:35:10,2018-06-05 13:24:00,2018-06-16 15:20:55,2018-07-18 00:00:00
27,dd78f560c270f1909639c11b925620ea,8b212b9525f9e74e85e37ed6df37693e,delivered,2018-03-12 01:50:26,2018-03-12 03:28:34,2018-03-12 21:06:37,2018-03-21 14:41:50,2018-03-28 00:00:00
28,91b2a010e1e45e6ba3d133fa997597be,cce89a605105b148387c52e286ac8335,delivered,2018-05-02 11:45:38,2018-05-03 12:55:01,2018-05-10 16:16:00,2018-05-16 20:56:24,2018-05-23 00:00:00
29,ecab90c9933c58908d3d6add7c6f5ae3,761df82feda9778854c6dafdaeb567e4,delivered,2018-02-25 13:50:30,2018-02-25 14:47:35,2018-02-26 22:28:50,2018-03-27 23:29:14,2018-04-13 00:00:00
30,f70a0aff17df5a6cdd9a7196128bd354,456dc10730fbdba34615447ea195d643,delivered,2017-08-10 11:58:33,2017-08-12 02:45:24,2017-08-17 15:35:07,2017-08-18 14:28:02,2017-08-23 00:00:00
31,1790eea0b567cf50911c057cf20f90f9,52142aa69d8d0e1247ab0cada0f76023,delivered,2018-04-16 21:15:39,2018-04-16 22:10:26,2018-04-18 13:05:09,2018-05-05 12:28:34,2018-05-15 00:00:00
32,989225ba6d0ebd5873335f7e01de2ae7,816f8653d5361cbf94e58c33f2502a5c,delivered,2017-12-12 13:56:04,2017-12-14 13:54:13,2017-12-16 00:18:57,2018-01-03 18:03:36,2018-01-08 00:00:00
33,d887b52c6516beb39e8cd44a5f8b60f7,d9ef95f98d8da3b492bb8c0447910498,delivered,2018-02-03 12:38:58,2018-02-03 12:50:30,2018-02-05 21:26:53,2018-02-22 00:07:55,2018-03-07 00:00:00
34,b276e4f8c0fb86bd82fce576f21713e0,cf8ffeddf027932e51e4eae73b384059,delivered,2018-07-29 23:34:51,2018-07-29 23:45:15,2018-07-30 14:43:00,2018-07-31 22:48:50,2018-08-06 00:00:00
35,8563039e855156e48fccee4d611a3196,5f16605299d698660e0606f7eae2d2f9,delivered,2018-02-17 15:59:46,2018-02-17 16:15:34,2018-02-20 23:03:56,2018-03-20 00:59:25,2018-03-20 00:00:00
36,60550084e6b4c0cb89a87df1f3e5ebd9,f5458ddc3545711efa883dd7ae7c4497,delivered,2018-02-21 18:15:12,2018-02-23 02:10:52,2018-02-27 18:52:09,2018-03-13 23:58:43,2018-03-29 00:00:00
37,5acce57f8d9dfd55fa48e212a641a69d,295ae9b35379e077273387ff64354b6f,delivered,2017-07-31 21:37:10,2017-08-02 02:56:02,2017-08-03 18:32:48,2017-08-08 21:24:41,2017-08-22 00:00:00
38,434d158e96bdd6972ad6e6d73ddcfd22,2a1dfb647f32f4390e7b857c67458536,delivered,2018-06-01 12:23:13,2018-06-05 03:35:15,2018-06-08 11:49:00,2018-06-18 21:32:52,2018-07-17 00:00:00
39,7206b86ea789983f7a273ea7fa0bc2a8,3391c4bc11a817e7973e498b0b023158,delivered,2018-03-26 17:12:18,2018-03-26 17:28:27,2018-03-28 17:22:53,2018-04-05 22:11:18,2018-04-12 00:00:00
40,1e7aff52cdbb2451ace09d0f848c3699,ddaff536587109b89777e0353215e150,delivered,2017-05-19 18:53:40,2017-05-19 19:05:17,2017-05-22 10:16:07,2017-05-31 13:58:46,2017-06-12 00:00:00
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21 00:00:00
42,948097deef559c742e7ce321e5e58919,8644be24d48806bc3a88fd59fb47ceb1,delivered,2017-08-04 17:10:39,2017-08-04 17:25:11,2017-08-07 17:52:01,2017-08-12 14:08:40,2017-09-01 00:00:00
43,d22e9fa5731b9e30e8b27afcdc2f8563,756fb9391752dad934e0fe3733378e57,delivered,2018-08-04 23:25:30,2018-08-04 23:35:13,2018-08-06 15:03:00,2018-08-13 23:34:42,2018-09-13 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
45,6ebaec694d7025e2ad4a05dba887c032,4f28355e5c17a4a42d3ce2439a1d4501,delivered,2017-05-18 13:55:47,2017-05-18 14:05:17,2017-05-19 12:01:38,2017-05-29 12:47:20,2017-06-09 00:00:00
46,d17dc4a904426827ca80f2ccb3a6be56,569cf68214806a39acc0f39344aea67f,delivered,2017-05-14 20:28:25,2017-05-14 20:42:45,2017-05-16 08:17:46,2017-05-25 09:14:31,2017-06-12 00:00:00
47,25f4376934e13d3508486352e11a5db0,12fd2740039676063a874b9567dfa651,delivered,2018-05-17 16:59:11,2018-05-18 01:17:39,2018-05-18 13:02:00,2018-05-21 15:22:11,2018-05-25 00:00:00
48,5820a1100976432c7968a52da59e9364,2b56e94c2f66f2d97cfa63356f69cee8,delivered,2018-07-29 11:24:17,2018-07-29 11:44:19,2018-07-30 13:47:00,2018-08-02 22:09:11,2018-08-13 00:00:00
49,2ce1ad82022c1ba30c2079502ac725aa,7f2178c5d771e17f507d3c1637339298,delivered,2017-08-09 20:19:05,2017-08-11 04:15:29,2017-08-11 17:52:32,2017-08-16 17:16:44,2017-08-31 00:00:00

In [17]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [18]:
order_items=pd.read_csv('Dataset/olist_order_items_dataset.csv')

In [19]:
order_items.shape

(112650, 7)

In [20]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [21]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [23]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [24]:
reviews=pd.read_csv('Dataset/olist_order_reviews_dataset.csv')
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [25]:
reviews.shape

(99224, 7)

In [26]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [27]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [29]:
reviews['order_id'].value_counts().head(10)

order_id
df56136b8031ecd28e200bb18e6ddb2e    3
c88b1d1b157a9999ce368f218a407141    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
029863af4b968de1e5d6a82782e662f5    2
29062384ce4975f78aeba6a496510386    2
bbf6a647ecc68aa5e79d2cd75ef44c68    2
7f13a20e25350f4a55fb2a7c9a2e8d88    2
aef2bc3845eb581cecce74b769d46c6a    2
0ed5043fe7d3f4f88353697330bbc020    2
Name: count, dtype: int64

In [30]:
reviews[['order_id', 'review_score']].head(20)

                            order_id  review_score
0   73fc7af87114b39712e6da79b0a377eb             4
1   a548910a1c6147796b98fdf73dbeba33             5
2   f9e4b658b201a9f2ecdecbb34bed034b             5
3   658677c97b385a9be170737859d3511b             5
4   8e6bfb81e283fa7e4f11123a3fb894f1             5
5   b18dcdf73be66366873cd26c5724d1dc             1
6   e48aa0d2dcec3a2e87348811bcfdf22b             5
7   c31a859e34e3adac22f376954e19b39d             5
8   9c214ac970e84273583ab523dfafd09b             5
9   b9bf720beb4ab3728760088589c62129             4
10  cdf9aa68e72324eeb25c7de974696ee2             5
11  3d374c9e46530bb5ed4a7648915306a6             5
12  9d6f15f95d01e79bd1349cc208361f09             4
13  2eaf8e099d871cd5c22b83b5ea8f6e0e             4
14  d7bd0e4afdf94846eb73642b4e3e75c3             3
15  e51478e7e277a83743b6f9991dbfa3fb             5
16  0dacf04c5ad59fd5a0cc1faa07c34e39             2
17  ff1581e08b3011021e7c7de592ddc81e             5
18  70a752414a13d09cc1f2b437b914b28e             3
19  583174fbe37d3d5f0d6661be3aad1786             1

In [31]:
reviews[reviews['order_id'] == 'df56136b8031ecd28e200bb18e6ddb2e']

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
2952,c444278834184f72b1484dfe47de7f97,df56136b8031ecd28e200bb18e6ddb2e,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48
13982,72a1098d5b410ae50fbc0509d26daeb9,df56136b8031ecd28e200bb18e6ddb2e,5,NaN,NaN,2017-02-07 00:00:00,2017-02-10 10:46:09
62728,44f3e54834d23c5570c1d010824d4d59,df56136b8031ecd28e200bb18e6ddb2e,5,NaN,NaN,2017-02-09 00:00:00,2017-02-09 09:07:28

In [32]:
reviews['order_id'].value_counts().value_counts()

count
1    98126
2      543
3        4
Name: count, dtype: int64

In [33]:
order_items.duplicated().sum()

np.int64(0)

In [35]:
reviews.duplicated().sum()

np.int64(0)

In [36]:
orders.duplicated().sum()

np.int64(0)

In [38]:
item_summary=order_items.groupby('order_id')['order_item_id'].count()

In [39]:
item_summary.head()

order_id
00010242fe8c5a6d1ba2dd792cb16214    1
00018f77f2f0320c557190d7a144bdd3    1
000229ec398224ef6ca0657da4fc703e    1
00024acbcdf0a6daa1e931b038114c75    1
00042b26cf59d7ce69dfabb4e55b4fd9    1
Name: order_item_id, dtype: int64

In [40]:
item_summary.value_counts()

order_item_id
1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
10        8
12        5
11        4
9         3
20        2
14        2
15        2
13        1
21        1
Name: count, dtype: int64

In [42]:
item_summary.head()

order_id
00010242fe8c5a6d1ba2dd792cb16214    1
00018f77f2f0320c557190d7a144bdd3    1
000229ec398224ef6ca0657da4fc703e    1
00024acbcdf0a6daa1e931b038114c75    1
00042b26cf59d7ce69dfabb4e55b4fd9    1
Name: order_item_id, dtype: int64

In [43]:
item_summary.value_counts().head()

order_item_id
1    88863
2     7516
3     1322
4      505
5      204
Name: count, dtype: int64

In [44]:
order_value=order_items.groupby('order_id')['price'].sum()

In [45]:
order_value.head()

order_id
00010242fe8c5a6d1ba2dd792cb16214     58.90
00018f77f2f0320c557190d7a144bdd3    239.90
000229ec398224ef6ca0657da4fc703e    199.00
00024acbcdf0a6daa1e931b038114c75     12.99
00042b26cf59d7ce69dfabb4e55b4fd9    199.90
Name: price, dtype: float64

In [48]:
item_summary=order_items.groupby('order_id')['order_item_id'].count().reset_index(name='item_count')

In [49]:
item_summary.head()

                           order_id  item_count
0  00010242fe8c5a6d1ba2dd792cb16214           1
1  00018f77f2f0320c557190d7a144bdd3           1
2  000229ec398224ef6ca0657da4fc703e           1
3  00024acbcdf0a6daa1e931b038114c75           1
4  00042b26cf59d7ce69dfabb4e55b4fd9           1

In [53]:
order_value=order_items.groupby('order_id')['price'].sum().reset_index(name="order_value")

In [54]:
order_value.head()

                           order_id  order_value
0  00010242fe8c5a6d1ba2dd792cb16214        58.90
1  00018f77f2f0320c557190d7a144bdd3       239.90
2  000229ec398224ef6ca0657da4fc703e       199.00
3  00024acbcdf0a6daa1e931b038114c75        12.99
4  00042b26cf59d7ce69dfabb4e55b4fd9       199.90

In [55]:
item_summary=item_summary.merge(order_value,on='order_id')

In [56]:
item_summary.head()

                           order_id  item_count  order_value
0  00010242fe8c5a6d1ba2dd792cb16214           1        58.90
1  00018f77f2f0320c557190d7a144bdd3           1       239.90
2  000229ec398224ef6ca0657da4fc703e           1       199.00
3  00024acbcdf0a6daa1e931b038114c75           1        12.99
4  00042b26cf59d7ce69dfabb4e55b4fd9           1       199.90

In [57]:
item_summary.duplicated().sum()

np.int64(0)

In [58]:
item_summary.shape

(98666, 3)

In [59]:
reviews['order_id'].nunique()

98673

In [61]:
reviews.duplicated().sum()

np.int64(0)

In [62]:
review_summary=reviews.groupby('order_id')['review_score'].mean().reset_index(name='review_score')

In [63]:
review_summary.head()

                           order_id  review_score
0  00010242fe8c5a6d1ba2dd792cb16214           5.0
1  00018f77f2f0320c557190d7a144bdd3           4.0
2  000229ec398224ef6ca0657da4fc703e           5.0
3  00024acbcdf0a6daa1e931b038114c75           4.0
4  00042b26cf59d7ce69dfabb4e55b4fd9           5.0

In [64]:
item_summary=item_summary.merge(review_summary,on='order_id')

In [65]:
item_summary.head()

                           order_id  item_count  order_value  review_score
0  00010242fe8c5a6d1ba2dd792cb16214           1        58.90           5.0
1  00018f77f2f0320c557190d7a144bdd3           1       239.90           4.0
2  000229ec398224ef6ca0657da4fc703e           1       199.00           5.0
3  00024acbcdf0a6daa1e931b038114c75           1        12.99           4.0
4  00042b26cf59d7ce69dfabb4e55b4fd9           1       199.90           5.0

In [66]:
orders['order_id'].nunique()

99441

In [67]:
order_data=orders.merge(item_summary,on='order_id',how='left')

In [69]:
order_data.shape

(99441, 11)

In [70]:
order_data.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'item_count', 'order_value', 'review_score'],
      dtype='object')

In [71]:
order_data[['order_delivered_customer_date', 'order_estimated_delivery_date']].dtypes

order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [73]:
order_data['order_delivered_customer_date']=pd.to_datetime(order_data['order_delivered_customer_date'])

In [74]:
order_data['order_estimated_delivery_date']=pd.to_datetime(order_data['order_estimated_delivery_date'])

In [75]:
order_data[['order_delivered_customer_date', 'order_estimated_delivery_date']].dtypes

order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [76]:
order_data['order_delivered_customer_date']-order_data['order_estimated_delivery_date']

0        -8 days +21:25:13
1        -6 days +15:27:45
2       -18 days +18:06:29
3       -13 days +00:28:42
4       -10 days +18:17:02
               ...
99436   -11 days +15:08:01
99437    -2 days +17:37:56
99438    -6 days +11:24:17
99439   -21 days +23:32:54
99440   -18 days +13:08:30
Length: 99441, dtype: timedelta64[ns]

In [83]:
delivered_orders=order_data[order_data['order_status']=='delivered']

In [84]:
delivered_orders.shape

(96478, 11)

In [86]:
delivered_orders = order_data[order_data['order_status'] == 'delivered'].copy()

In [87]:
delivered_orders['delivery_difference'] = (
    delivered_orders['order_delivered_customer_date']
    - delivered_orders['order_estimated_delivery_date']
)

In [88]:
delivered_orders.shape

(96478, 12)

In [89]:
delivered_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,item_count,order_value,review_score,delivery_difference
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,29.99,4.0,-8 days +21:25:13
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.0,118.70,4.0,-6 days +15:27:45
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1.0,159.90,5.0,-18 days +18:06:29
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1.0,45.00,5.0,-13 days +00:28:42
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1.0,19.90,5.0,-10 days +18:17:02

In [90]:
delivered_orders['delivery_difference'].dt.days

0        -8.0
1        -6.0
2       -18.0
3       -13.0
4       -10.0
         ...
99436   -11.0
99437    -2.0
99438    -6.0
99439   -21.0
99440   -18.0
Name: delivery_difference, Length: 96478, dtype: float64

In [91]:
delivered_orders['days_late']=delivered_orders['delivery_difference'].dt.days.clip(lower=0)

In [93]:
delivered_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'item_count', 'order_value', 'review_score', 'delivery_difference',
       'days_late'],
      dtype='object')

In [95]:
delivered_orders.head(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,item_count,order_value,review_score,delivery_difference,days_late
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,29.99,4.0,-8 days +21:25:13,0.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.0,118.70,4.0,-6 days +15:27:45,0.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1.0,159.90,5.0,-18 days +18:06:29,0.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1.0,45.00,5.0,-13 days +00:28:42,0.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1.0,19.90,5.0,-10 days +18:17:02,0.0
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,1.0,147.90,4.0,-6 days +10:57:55,0.0
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,1.0,59.99,5.0,-12 days +12:55:51,0.0
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,1.0,19.90,1.0,-32 days +14:08:10,0.0
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,1.0,149.99,5.0,-7 days +17:14:30,0.0
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,2.0,198.00,1.0,-9 days +11:18:31,0.0
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08,1.0,98.00,4.0,-20 days +14:04:48,0.0
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18,1.0,31.90,5.0,-29 days +12:05:52,0.0
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08,1.0,19.90,5.0,-9 days +15:52:25,0.0
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21,1.0,38.25,4.0,-9 days +23:36:26,0.0
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04,1.0,132.40,5.0,-13 days +15:34:32,0.0
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06,NaN,NaN,NaN,-17 days +01:38:59,0.0
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29,1.0,27.99,5.0,-21 days +22:36:36,0.0
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11,1.0,17.90,5.0,-14 days +18:28:00,0.0
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23,1.0,76.00,4.0,-15 days +22:22:00,0.0
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,1.0,109.90,2.0,11 days 22:23:46,11.0

In [96]:
delivered_orders['order_id'].is_unique

True

In [99]:
delivered_orders[['item_count', 'order_value', 'review_score']].isnull().sum()

item_count      646
order_value     646
review_score    646
dtype: int64

In [100]:
delivered_orders['item_count'].isnull().sum()

np.int64(646)

In [101]:
delivered_orders[
    delivered_orders['item_count'].isnull()
][['order_id', 'order_status']]

                               order_id order_status
16     403b97836b0c04a622354cf531062e5f    delivered
311    4906eeadde5f70b308c20c4a8f20be02    delivered
382    b7a4a9ecb1cd3ef6a3e36a48e200e3be    delivered
390    59b32faedc12322c672e95ec3716d614    delivered
409    c2215076050fa358934105b15c34cf3b    delivered
...                                 ...          ...
98697  0c384d67524b5b92aa2fa6c8baa9a983    delivered
98781  906a6b0a96d89ee226e4977e99b80b9e    delivered
99007  5333db16fe357175d39c82840dd3269d    delivered
99134  2f2df159f26ddb73d55ee72372200d3e    delivered
99245  dff2b9b8d7cfc595836945e1443789c3    delivered

[646 rows x 2 columns]

In [102]:
order_items[order_items['order_id'] == '403b97836b0c04a622354cf531062e5f']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
28206,403b97836b0c04a622354cf531062e5f,1,638bbb2a5e4f360b71f332ddfebfd672,c4af86330efa7a2620772227d2d670c9,2018-01-12 19:09:04,1299.0,77.45

In [103]:
item_summary[item_summary['order_id'] == '403b97836b0c04a622354cf531062e5f']

Empty DataFrame
Columns: [order_id, item_count, order_value, review_score]
Index: []

In [104]:
item_summary.shape

(97917, 4)

In [105]:
item_summary = order_items.groupby('order_id').agg(
    item_count=('order_item_id', 'count'),
    order_value=('price', 'sum')
).reset_index()

In [106]:
item_summary.shape

(98666, 3)

In [107]:
item_summary = item_summary.merge(review_summary, on='order_id', how='left')

In [108]:
item_summary.shape

(98666, 4)

In [109]:
order_data = orders.merge(item_summary, on='order_id', how='left')

In [110]:
order_data.shape

(99441, 11)

In [111]:
order_data[['item_count', 'order_value', 'review_score']].isnull().sum()

item_count       775
order_value      775
review_score    1524
dtype: int64

In [112]:
delivered_orders = order_data[order_data['order_status'] == 'delivered'].copy()

In [113]:
delivered_orders[['item_count', 'order_value', 'review_score']].isnull().sum()

item_count        0
order_value       0
review_score    646
dtype: int64

In [114]:
(delivered_orders['order_delivered_customer_date'] < delivered_orders['order_purchase_timestamp']).sum()

np.int64(0)

In [116]:
check = order_items.groupby('order_id')['price'].sum().reset_index(name='raw_order_value')

In [117]:
check = check.merge(
    delivered_orders[['order_id', 'order_value']],
    on='order_id',
    how='inner'
)

In [118]:
check['difference'] = check['raw_order_value'] - check['order_value']

In [119]:
(check['difference'] != 0).sum()

np.int64(0)

In [122]:
delivered_orders['order_delivered_customer_date'] = pd.to_datetime(
    delivered_orders['order_delivered_customer_date']
)

In [123]:
delivered_orders['order_estimated_delivery_date'] = pd.to_datetime(
    delivered_orders['order_estimated_delivery_date']
)

In [124]:
delivered_orders['delivery_difference'] = (
    delivered_orders['order_delivered_customer_date']
    - delivered_orders['order_estimated_delivery_date']
)

In [125]:
delivered_orders['days_late'] = delivered_orders['delivery_difference'].dt.days.clip(lower=0)

In [126]:
delivered_orders[['order_id', 'order_delivered_customer_date',
                  'order_estimated_delivery_date', 'days_late',
                  'item_count', 'order_value', 'review_score']].head()

,order_id,order_delivered_customer_date,order_estimated_delivery_date,days_late,item_count,order_value,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-10 21:25:13,2017-10-18,0.0,1.0,29.99,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,2018-08-07 15:27:45,2018-08-13,0.0,1.0,118.70,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-17 18:06:29,2018-09-04,0.0,1.0,159.90,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-12-02 00:28:42,2017-12-15,0.0,1.0,45.00,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-16 18:17:02,2018-02-26,0.0,1.0,19.90,5.0

In [127]:
delivered_orders = delivered_orders.drop(columns=['delivery_difference'])

In [128]:
delivered_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,item_count,order_value,review_score,days_late
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,29.99,4.0,0.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.0,118.70,4.0,0.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1.0,159.90,5.0,0.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1.0,45.00,5.0,0.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1.0,19.90,5.0,0.0

In [129]:
delivered_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'item_count', 'order_value', 'review_score', 'days_late'],
      dtype='object')

In [130]:
delivered_orders.shape

(96478, 12)

In [133]:
delivered_orders.to_csv("olist_delivered_orders.csv",index=False)

In [134]:
import os

os.path.exists("olist_delivered_orders.csv")

True

In [135]:
final_check = pd.read_csv("olist_delivered_orders.csv")

final_check.shape

(96478, 12)

In [136]:
reviews = pd.read_csv("Dataset/olist_order_reviews_dataset.csv")

In [137]:
reviews.shape

(99224, 7)

In [138]:
reviews_with_comments = reviews[
    reviews['review_comment_message'].notna()
].copy()

In [139]:
reviews_with_comments.shape

(40977, 7)

In [140]:
sample_reviews = reviews_with_comments.sample(
    n=200,
    random_state=42
).copy()

In [141]:
sample_reviews.shape

(200, 7)

In [142]:
sample_reviews[['order_id', 'review_score', 'review_comment_message']].head(10)

,order_id,review_score,review_comment_message
37062,301b453872955e08f7aed322d6a0753a,4,Um produto como uma carteira somente poderia s...
17697,f9281da15642bc69f27307e1dc987b30,5,"Entrega no prazo , bom produto ."
41606,e747b099854432937d27178c640102bf,5,entrega rápida
41683,3f3e4083688c07129239450773e84282,5,Chegou no prazo e atendeu as minhas espectativas
75879,b3b8133868458b6acf08ea6ffc22e3f2,5,Logística ótima entregue antes do prazo previs...
9996,a4244008bc97ae9cdc3807237fa83229,5,"Entrega no prazo combinado , chegou certinho r..."
49544,2b4d04cfb81d2dbb1ab48f9e2a7ac6b9,1,Vocês me enviaram faltando 3 cortinas. E agora?
33742,c38db22a86ae94a2a5a9dd2d5700f6cb,4,A encomenda demorou muito a chegar mas chegou ...
22167,fde2b2f46bb69e2359b74ff7606de899,4,produto dentro do esperado sem defeitos
29629,7cc23d880ead6eb7ebecb6292435b6d6,4,Chegou no prazo !

In [143]:
sample_reviews = sample_reviews.merge(
    delivered_orders[['order_id', 'days_late']],
    on='order_id',
    how='left'
)

In [144]:
sample_reviews[['order_id', 'days_late']].head(10)

                           order_id  days_late
0  301b453872955e08f7aed322d6a0753a        0.0
1  f9281da15642bc69f27307e1dc987b30        0.0
2  e747b099854432937d27178c640102bf        0.0
3  3f3e4083688c07129239450773e84282        0.0
4  b3b8133868458b6acf08ea6ffc22e3f2        0.0
5  a4244008bc97ae9cdc3807237fa83229        0.0
6  2b4d04cfb81d2dbb1ab48f9e2a7ac6b9        0.0
7  c38db22a86ae94a2a5a9dd2d5700f6cb        9.0
8  fde2b2f46bb69e2359b74ff7606de899        0.0
9  7cc23d880ead6eb7ebecb6292435b6d6        0.0

In [145]:
sample_reviews['delivery_status'] = sample_reviews['days_late'].apply(
    lambda x: 'Late' if x > 0 else 'On-Time'
)

In [146]:
sample_reviews['delivery_status'].value_counts()

delivery_status
On-Time    179
Late        21
Name: count, dtype: int64

In [148]:
claude_input = sample_reviews[
    ['order_id', 'review_comment_message', 'delivery_status']
].copy()

claude_input.head()

,order_id,review_comment_message,delivery_status
0,301b453872955e08f7aed322d6a0753a,Um produto como uma carteira somente poderia s...,On-Time
1,f9281da15642bc69f27307e1dc987b30,"Entrega no prazo , bom produto .",On-Time
2,e747b099854432937d27178c640102bf,entrega rápida,On-Time
3,3f3e4083688c07129239450773e84282,Chegou no prazo e atendeu as minhas espectativas,On-Time
4,b3b8133868458b6acf08ea6ffc22e3f2,Logística ótima entregue antes do prazo previs...,On-Time

In [149]:
claude_input = claude_input.reset_index(drop=True)
claude_input['review_number'] = claude_input.index + 1

claude_input[['review_number', 'order_id', 'review_comment_message', 'delivery_status']].head()

,review_number,order_id,review_comment_message,delivery_status
0,1,301b453872955e08f7aed322d6a0753a,Um produto como uma carteira somente poderia s...,On-Time
1,2,f9281da15642bc69f27307e1dc987b30,"Entrega no prazo , bom produto .",On-Time
2,3,e747b099854432937d27178c640102bf,entrega rápida,On-Time
3,4,3f3e4083688c07129239450773e84282,Chegou no prazo e atendeu as minhas espectativas,On-Time
4,5,b3b8133868458b6acf08ea6ffc22e3f2,Logística ótima entregue antes do prazo previs...,On-Time

In [150]:
claude_input[['review_number', 'order_id']].head(10)

   review_number                          order_id
0              1  301b453872955e08f7aed322d6a0753a
1              2  f9281da15642bc69f27307e1dc987b30
2              3  e747b099854432937d27178c640102bf
3              4  3f3e4083688c07129239450773e84282
4              5  b3b8133868458b6acf08ea6ffc22e3f2
5              6  a4244008bc97ae9cdc3807237fa83229
6              7  2b4d04cfb81d2dbb1ab48f9e2a7ac6b9
7              8  c38db22a86ae94a2a5a9dd2d5700f6cb
8              9  fde2b2f46bb69e2359b74ff7606de899
9             10  7cc23d880ead6eb7ebecb6292435b6d6

In [151]:
claude_input = claude_input.reset_index(drop=True)
claude_input['review_number'] = claude_input.index + 1

In [152]:
claude_input[['review_number', 'order_id']].head(10)

   review_number                          order_id
0              1  301b453872955e08f7aed322d6a0753a
1              2  f9281da15642bc69f27307e1dc987b30
2              3  e747b099854432937d27178c640102bf
3              4  3f3e4083688c07129239450773e84282
4              5  b3b8133868458b6acf08ea6ffc22e3f2
5              6  a4244008bc97ae9cdc3807237fa83229
6              7  2b4d04cfb81d2dbb1ab48f9e2a7ac6b9
7              8  c38db22a86ae94a2a5a9dd2d5700f6cb
8              9  fde2b2f46bb69e2359b74ff7606de899
9             10  7cc23d880ead6eb7ebecb6292435b6d6

In [153]:
batch_1 = claude_input.iloc[0:20][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

batch_1

,review_number,order_id,review_comment_message
0,1,301b453872955e08f7aed322d6a0753a,Um produto como uma carteira somente poderia s...
1,2,f9281da15642bc69f27307e1dc987b30,"Entrega no prazo , bom produto ."
2,3,e747b099854432937d27178c640102bf,entrega rápida
3,4,3f3e4083688c07129239450773e84282,Chegou no prazo e atendeu as minhas espectativas
4,5,b3b8133868458b6acf08ea6ffc22e3f2,Logística ótima entregue antes do prazo previs...
5,6,a4244008bc97ae9cdc3807237fa83229,"Entrega no prazo combinado , chegou certinho r..."
6,7,2b4d04cfb81d2dbb1ab48f9e2a7ac6b9,Vocês me enviaram faltando 3 cortinas. E agora?
7,8,c38db22a86ae94a2a5a9dd2d5700f6cb,A encomenda demorou muito a chegar mas chegou ...
8,9,fde2b2f46bb69e2359b74ff7606de899,produto dentro do esperado sem defeitos
9,10,7cc23d880ead6eb7ebecb6292435b6d6,Chegou no prazo !
10,11,6fa507b714ac24b88af01fdc92ccb77c,S
11,12,8e5a8b1f6cf7513edaf3bf7c5573ebf4,"Produto ótimo, a entrega deixou a desejar"
12,13,d55d7b1f89a06d58b4ee58e148dcbe4c,Ainda não recebi meu produto não dá pra avaliar
13,14,f09afa8a9cfcfba64cb18282881fe509,Top
14,15,79779a656c87065c8e3ff7f7510e08a6,Gostaria que as entregas fossem mais rápidas.
15,16,016706d732e79b49035275c048edb2c4,Quero estorno do meu dinheiro o mais rápido po...
16,17,05297254c9e41d34c1a38f75ca8656d9,Produto muito bom mais o prazo nao.foi cumprido
17,18,156254aa58b87bb7bad0f9e82f9bd5f9,"Olá, o produto veio com o conctor faltando. Po..."
18,19,7fb9a8071a075a78c82420971e66dd77,Não é um produto que chega e é passível de ins...
19,20,25fbf27ebf14d822b62827aeb77d9d10,Ok

In [156]:
for _, row in batch_1.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 1
Review: Um produto como uma carteira somente poderia ser avaliado depois de algum tempo de uso, No entanto, o produto é bem acabado e de couro conforme o especificado pela empresa.
--------------------------------------------------------------------------------
Review number: 2
Review: Entrega no prazo , bom produto .
--------------------------------------------------------------------------------
Review number: 3
Review: entrega rápida
--------------------------------------------------------------------------------
Review number: 4
Review: Chegou no prazo e atendeu as minhas espectativas
--------------------------------------------------------------------------------
Review number: 5
Review: Logística ótima entregue antes do prazo previsto, estou satisfeito.
--------------------------------------------------------------------------------
Review number: 6
Review: Entrega no prazo combinado , chegou certinho recomendo esse loja
--------------------------------------------------------------------------------
Review number: 7
Review: Vocês me enviaram faltando 3 cortinas. E agora?
--------------------------------------------------------------------------------
Review number: 8
Review: A encomenda demorou muito a chegar mas chegou em perfeito estado.
--------------------------------------------------------------------------------
Review number: 9
Review: produto dentro do esperado sem defeitos
--------------------------------------------------------------------------------
Review number: 10
Review: Chegou no prazo !
--------------------------------------------------------------------------------
Review number: 11
Review: S
--------------------------------------------------------------------------------
Review number: 12
Review: Produto ótimo, a entrega deixou a desejar
--------------------------------------------------------------------------------
Review number: 13
Review: Ainda não recebi meu produto não dá pra avaliar
--------------------------------------------------------------------------------
Review number: 14
Review: Top
--------------------------------------------------------------------------------
Review number: 15
Review: Gostaria que as entregas fossem mais rápidas.
--------------------------------------------------------------------------------
Review number: 16
Review: Quero estorno do meu dinheiro o mais rápido possível ou ainda aceito a entrega do meu produto
--------------------------------------------------------------------------------
Review number: 17
Review: Produto muito bom mais o prazo nao.foi cumprido
--------------------------------------------------------------------------------
Review number: 18
Review: Olá, o produto veio com o conctor faltando. Por favor, podem me enviar?

Aguardo.
--------------------------------------------------------------------------------
Review number: 19
Review: Não é um produto que chega e é passível de instalação. Sem manual, é necessário entrar em contato com a empreaa fabricante. Um produto caro que exige plataforma Windows para instalação e configuração.
--------------------------------------------------------------------------------
Review number: 20
Review: Ok
--------------------------------------------------------------------------------

In [157]:
batch_2 = claude_input.iloc[20:40][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_2.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 21
Review: Quero trocar o produto. Tecido da cortina mega fino
--------------------------------------------------------------------------------
Review number: 22
Review: Recebi o produto antes da data estipulada porem as tampas vieram quebradas como se não suportasse o produto dentro da embalagem (embalagem pequena).
--------------------------------------------------------------------------------
Review number: 23
Review: Meu filho amou a mochila... Perfeita..e melhor ainda chegou justo no aniversário dele.
--------------------------------------------------------------------------------
Review number: 24
Review: desde pedido não vieram as almofadas ainda
--------------------------------------------------------------------------------
Review number: 25
Review: Boa!
--------------------------------------------------------------------------------
Review number: 26
Review: Td certo com a entrega
--------------------------------------------------------------------------------
Review number: 27
Review: Produtos com qualidade, entregues antes do prazo.
--------------------------------------------------------------------------------
Review number: 28
Review: Muito bom
--------------------------------------------------------------------------------
Review number: 29
Review: Recebi o produto antes do prazo estimado. O produto esta em teste. Vamos avaliar se corresponde ao que esperamos. Por enquanto vou avaliar com 03 estrelas.
--------------------------------------------------------------------------------
Review number: 30
Review: Gostei da compra produto de qualidade..chegou antes do ora só previsto..
--------------------------------------------------------------------------------
Review number: 31
Review: Comprei de 240 tabletes e veio 120 entrei com pedido de troca estou aguardando resposta.Dependendo de como a loja parceira resolverá meu problema direi se indico ou ñ.
--------------------------------------------------------------------------------
Review number: 32
Review: Entrega muito rápida
--------------------------------------------------------------------------------
Review number: 33
Review: Comprei 3 garrafas de vinho veio so duas e agora reclamar como se assinei
--------------------------------------------------------------------------------
Review number: 34
Review: Prezados,
O produto estragou na hora de conectar com o aparelho de 110 volts na rede de 220.
Como faço para voces enviarem outro?
--------------------------------------------------------------------------------
Review number: 35
Review: O carregador anunciado não confere com o entregue, na caixa do produto vem até escrito a amperagem qual eu necessitava ,porém no carregador consta metade da amperagem oferecida pelo vendedor
--------------------------------------------------------------------------------
Review number: 36
Review: São duas peças e eu só recebi uma
--------------------------------------------------------------------------------
Review number: 37
Review: o produto ainda não instalei mas a entrega foi super rápido
--------------------------------------------------------------------------------
Review number: 38
Review: Só problema é que não avisa que é preciso ter um cartucho
--------------------------------------------------------------------------------
Review number: 39
Review: otimo produto chegou em boas condições
--------------------------------------------------------------------------------
Review number: 40
Review: Além do produto ser bom, a entrega foi super rápida.
Esse eu indico.
--------------------------------------------------------------------------------

In [158]:
validation_30 = pd.DataFrame({
    'review_number': list(range(1, 31)),
    'chatgpt_theme': [
        # Reviews 1–20
        'product_quality',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'wrong_or_missing_item',
        'late_or_not_received',
        'product_quality',
        'good_experience',
        'other',
        'late_or_not_received',
        'late_or_not_received',
        'good_experience',
        'late_or_not_received',
        'late_or_not_received',
        'late_or_not_received',
        'wrong_or_missing_item',
        'product_quality',
        'other',

        # Reviews 21–30
        'product_quality',
        'product_quality',
        'good_experience',
        'wrong_or_missing_item',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience'
    ],
    'manual_theme': [
        # Reviews 1–20
        'product_quality',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'wrong_or_missing_item',
        'late_or_not_received',
        'product_quality',
        'good_experience',
        'other',
        'late_or_not_received',
        'late_or_not_received',
        'good_experience',
        'late_or_not_received',
        'late_or_not_received',
        'late_or_not_received',
        'wrong_or_missing_item',
        'product_quality',
        'other',

        # Reviews 21–30
        'product_quality',
        'product_quality',
        'good_experience',
        'wrong_or_missing_item',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience',
        'good_experience'
    ]
})

validation_30['correct'] = (
    validation_30['chatgpt_theme'] ==
    validation_30['manual_theme']
)

validation_30

    review_number          chatgpt_theme           manual_theme  correct
0               1        product_quality        product_quality     True
1               2        good_experience        good_experience     True
2               3        good_experience        good_experience     True
3               4        good_experience        good_experience     True
4               5        good_experience        good_experience     True
5               6        good_experience        good_experience     True
6               7  wrong_or_missing_item  wrong_or_missing_item     True
7               8   late_or_not_received   late_or_not_received     True
8               9        product_quality        product_quality     True
9              10        good_experience        good_experience     True
10             11                  other                  other     True
11             12   late_or_not_received   late_or_not_received     True
12             13   late_or_not_received   late_or_not_received     True
13             14        good_experience        good_experience     True
14             15   late_or_not_received   late_or_not_received     True
15             16   late_or_not_received   late_or_not_received     True
16             17   late_or_not_received   late_or_not_received     True
17             18  wrong_or_missing_item  wrong_or_missing_item     True
18             19        product_quality        product_quality     True
19             20                  other                  other     True
20             21        product_quality        product_quality     True
21             22        product_quality        product_quality     True
22             23        good_experience        good_experience     True
23             24  wrong_or_missing_item  wrong_or_missing_item     True
24             25        good_experience        good_experience     True
25             26        good_experience        good_experience     True
26             27        good_experience        good_experience     True
27             28        good_experience        good_experience     True
28             29        good_experience        good_experience     True
29             30        good_experience        good_experience     True

In [159]:
accuracy_30 = validation_30['correct'].mean()

print(f"Correct classifications: {validation_30['correct'].sum()} / {len(validation_30)}")
print(f"Accuracy: {accuracy_30:.0%}")

Correct classifications: 30 / 30
Accuracy: 100%

In [160]:
batch_3 = claude_input.iloc[40:60][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_3.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 41
Review: Ótima compra para quem tem pouco espaço pra secar roupas.
--------------------------------------------------------------------------------
Review number: 42
Review: Ate agora comprei o transformador de voltagem 9000 btu nao recebi liguei pra americana a atendente me falou q ia liga pra transportadora e mr retorno em dois dias ja se passaram o prazo .
--------------------------------------------------------------------------------
Review number: 43
Review: FOI CANCELADO. COMO FAÇO PARA FAZER OUTRO PEDIDO CO O VALOR PAGO ?
--------------------------------------------------------------------------------
Review number: 44
Review: A empresa targaryen deixou a desejar com o envio do produto na cor errada.
--------------------------------------------------------------------------------
Review number: 45
Review: Muito bom!
--------------------------------------------------------------------------------
Review number: 46
Review: achei que demoro mais que os outros pedidos...
--------------------------------------------------------------------------------
Review number: 47
Review: O produto custou R$34 com frete, mas não é bom. É bem ralinho parece água.
--------------------------------------------------------------------------------
Review number: 48
Review: Produto excelente. Facil uso. Recomendo.
--------------------------------------------------------------------------------
Review number: 49
Review: No site o produto parece ter melhor qualidade de material e acabamento.
--------------------------------------------------------------------------------
Review number: 50
Review: Excelente produto. Bom para qq fotógrafo.
--------------------------------------------------------------------------------
Review number: 51
Review: Não gostei pois me mandaram um produto perto e vencer o prazo de validade. Recedi o produto de 1kg no final do mês de abril com a validade para vencer agora no mês de julho .Gostaria de efetuar troca.
--------------------------------------------------------------------------------
Review number: 52
Review: Boa tarde,
Gostei muito do serviço e espero ser atendida bem assim na próxima compra!
--------------------------------------------------------------------------------
Review number: 53
Review: só acho que o frete é muito caro, eu evitaria comprar novamente
--------------------------------------------------------------------------------
Review number: 54
Review: O produto chegou certinho, antes do prazo, bem embalado e sem avarias.
--------------------------------------------------------------------------------
Review number: 55
Review: O produto é realmente de boa qualidade e confere com o desenho publicado.
--------------------------------------------------------------------------------
Review number: 56
Review: Excelencia. Sempre compro aqui
--------------------------------------------------------------------------------
Review number: 57
Review: Confiável, rápido e com Bom Preço.
--------------------------------------------------------------------------------
Review number: 58
Review: O relógio não era original e a foto do anuncio não batia com o qual recebi. Produto de pessima qualidade.
--------------------------------------------------------------------------------
Review number: 59
Review: Chegou bem antes do prazo, é o produto é de excelente qualidade!
--------------------------------------------------------------------------------
Review number: 60
Review: O produto ainda ano foi entregue.
--------------------------------------------------------------------------------

In [161]:
batch_4 = claude_input.iloc[60:80][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_4.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 61
Review: Cumpriu o acordado!
--------------------------------------------------------------------------------
Review number: 62
Review: Recebi a película e ela veio toda lacrada, porém no momento de colocá-la estava com problemas, riscos na tela e falta de cola em torno, ou seja, produto de má qualidade.
--------------------------------------------------------------------------------
Review number: 63
Review: O kit de cloreto de magnésio vale mais a pena do que comprar individualmente nas farmácias e drogarias.
--------------------------------------------------------------------------------
Review number: 64
Review: A entrega foi rápida, o produto superou as minhas expectativas, pena que o recarregador de baterias veio com um pequeno defeito de fabricacao, ma nada que comprometa a lanterna.
--------------------------------------------------------------------------------
Review number: 65
Review: Produto bem embalado. Entrega demorou mais que as concorrentes, porém foi 2 dias antes de vencer o prazo.
--------------------------------------------------------------------------------
Review number: 66
Review: Muito bom
--------------------------------------------------------------------------------
Review number: 67
Review: Recomendo esta loja pela qualidade, preço e rapidez na entrega.
--------------------------------------------------------------------------------
Review number: 68
Review: sempre compro com voces,porem dessa vez o produto que comprei deu problema no prazo de entrega
--------------------------------------------------------------------------------
Review number: 69
Review: Ótimo produto.
--------------------------------------------------------------------------------
Review number: 70
Review: Dedoches são muito lindos! Meu filho amou! Foi entregue dentro do prazo e intacto. Super recomendo!
--------------------------------------------------------------------------------
Review number: 71
Review: Serei cliente c frequência..

--------------------------------------------------------------------------------
Review number: 72
Review: péssima embalagem , tive que colar ele todo, fique com preguiça pelo preço de mandar de volta, mas não indico pra ninguém a loja...
--------------------------------------------------------------------------------
Review number: 73
Review: otimo atendimento
--------------------------------------------------------------------------------
Review number: 74
Review: Tudo certo na entrega é produto muito bom recomendo
--------------------------------------------------------------------------------
Review number: 75
Review: a caixa estava meia aberta e a data de garantia que não sei se é a validade está muito proxima 06/2018

--------------------------------------------------------------------------------
Review number: 76
Review: Tudo certo!
--------------------------------------------------------------------------------
Review number: 77
Review: Mercadoria perfeita recomendo a todos parabéns pelo trabalho de vcs
--------------------------------------------------------------------------------
Review number: 78
Review: gostei
--------------------------------------------------------------------------------
Review number: 79
Review: Eu comprei nas lannister, por se tratar de uma loja de confiança, porém ao chegar o produto descobri que o que foi vendido pela marca Targus, era na verdade um produto falsificado, não confio mais
--------------------------------------------------------------------------------
Review number: 80
Review: nao recebido
--------------------------------------------------------------------------------

In [162]:
batch_5 = claude_input.iloc[80:100][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_5.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 81
Review: Atendeu minhas expectativas,chegou antes do prazo,tecido lindo e de boa qualidade.Amei.
--------------------------------------------------------------------------------
Review number: 82
Review: Comprei o produto para honda biz. No entanto na embalagem havia escrito e marcado para handa broz.
--------------------------------------------------------------------------------
Review number: 83
Review: Recebi no prazo e já apliquei. Ficou muito bom e de fácil aplicação, mesmo pra mim que não tenho muita habilidade pra isso. Agora é só esperar para ver a durabilidade.
--------------------------------------------------------------------------------
Review number: 84
Review: Aí, adorei, chegou bem antes do prazo, e a armação é lindaaaaa, do jeitinho que eu queria
--------------------------------------------------------------------------------
Review number: 85
Review: Eu não recebi os dois produtos falta
Kit tapetes para cozinha 3 peças pintado à mão - Cru
1 unidade - R$ 35,00 cada


--------------------------------------------------------------------------------
Review number: 86
Review: Ótimo
--------------------------------------------------------------------------------
Review number: 87
Review: Produto original, bom preço e entrega rápida!!!
--------------------------------------------------------------------------------
Review number: 88
Review: Eu não tenho notícias do pedido anos do se e o correio da minha cidade
--------------------------------------------------------------------------------
Review number: 89
Review: Ainda não recebi o cinto.
--------------------------------------------------------------------------------
Review number: 90
Review: Recebi o produto corretamente conforme compra .
--------------------------------------------------------------------------------
Review number: 91
Review: excelente produto, entrega super agil
--------------------------------------------------------------------------------
Review number: 92
Review: Paguei mais caro e esperei mais tempo pra receber escovas Dourada e Branca...

No fim das contas recebi 2 escovas ROSA.
--------------------------------------------------------------------------------
Review number: 93
Review: Comprei uma capinha transparente e veio uma marmotenta colorida... ridículo..
--------------------------------------------------------------------------------
Review number: 94
Review: Bom dia , eu só queria entender , o por quê vocês colocam quê não será entregue em minha residência,quê será entregue ná agência dos Correios mais próxima,sendo-quê,o frete foi incluso na compra?
--------------------------------------------------------------------------------
Review number: 95
Review: Ótimo produto!
--------------------------------------------------------------------------------
Review number: 96
Review: O produto entregue não foi o produto comprado por mim, o pedido foi feito para o Aspirador De Pó Ph Rapid 1000N 127V e foi entregue ASP PO RAPID TURBO PAS02 127V, Desejo devolução do valor pago e reti
--------------------------------------------------------------------------------
Review number: 97
Review: Excelente!
--------------------------------------------------------------------------------
Review number: 98
Review: Excelente. Entrega dentro do prazo. Produto muito bem embalado.
--------------------------------------------------------------------------------
Review number: 99
Review: Relógio ótimo, como na descrição
--------------------------------------------------------------------------------
Review number: 100
Review: Muito bom. Adorei.
--------------------------------------------------------------------------------

In [163]:
batch_6 = claude_input.iloc[100:140][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_6.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 101
Review: E uma ótima plataforma de compra
--------------------------------------------------------------------------------
Review number: 102
Review: otima entrega
--------------------------------------------------------------------------------
Review number: 103
Review: O produto, é exatamente como esperava.perfeito.
--------------------------------------------------------------------------------
Review number: 104
Review: foi muito bom comprar com vcs obrigada!!!
--------------------------------------------------------------------------------
Review number: 105
Review: Produto não foi entregue e já entrei em contato com a lannister que ainda neo deu retorno
--------------------------------------------------------------------------------
Review number: 106
Review: produto chegou antes do prazo, cuidadosamente bem embalado, lindo pendente! recomendo.
--------------------------------------------------------------------------------
Review number: 107
Review: otimo produto
--------------------------------------------------------------------------------
Review number: 108
Review: Tive que ir no correio buscar a mercadoria, além de ter pago o frete para receber em minha residência.
--------------------------------------------------------------------------------
Review number: 109
Review: Produto excelente e de ótima qualidade. Adorei.
--------------------------------------------------------------------------------
Review number: 110
Review: Bom
--------------------------------------------------------------------------------
Review number: 111
Review: Chegou antes da data prevista, me deixou muito contente! Produto de ótima qualidade!
--------------------------------------------------------------------------------
Review number: 112
Review: O produto é um plástico Duro, vamos ver se suporta o aquecimento da lâmpada.
--------------------------------------------------------------------------------
Review number: 113
Review: fui bem atendido, mas o valor cobrado foi divergente do valor apresentado no site(desconto de 5% pela forma de pagamento). mas tudo ja foi resolvido.
--------------------------------------------------------------------------------
Review number: 114
Review: produto de má qualidade
--------------------------------------------------------------------------------
Review number: 115
Review: A demora pra entrega é maior que de outros produtos e isso é desanimador
--------------------------------------------------------------------------------
Review number: 116
Review: Ótimo produto, entrega rápida, minha esposa esta extremamente satisfeita, me dei bem !!
--------------------------------------------------------------------------------
Review number: 117
Review: Produto de qualidade conforme anunciado, entrega antes do combinado.
--------------------------------------------------------------------------------
Review number: 118
Review: Veio super rapido excelente
--------------------------------------------------------------------------------
Review number: 119
Review: Ja enviei varios emails reclamando sobre a entrega do produto e n me respondem
--------------------------------------------------------------------------------
Review number: 120
Review: Achei apenas que o acabamento da peça podia ser melhor.
--------------------------------------------------------------------------------
Review number: 121
Review: Supero minhas expectativas. Muito bom o produto.
--------------------------------------------------------------------------------
Review number: 122
Review: Paguei pelo Kit completo:shampoo,condicionador e ativador de cachos e recebi apenas o ativador de cachos,isso tá errado

--------------------------------------------------------------------------------
Review number: 123
Review: O produto chegou antes do previsto veio certinho conforme o descrito no site e veio bem embalado.
--------------------------------------------------------------------------------
Review number: 124
Review: recomendo! tudo como esperado e dentro do prazo!
--------------------------------------------------------------------------------
Review number: 125
Review: Muito boa loja
--------------------------------------------------------------------------------
Review number: 126
Review: Muito rápida a entrega!!!
--------------------------------------------------------------------------------
Review number: 127
Review: não veio o produto que eu comprei.
--------------------------------------------------------------------------------
Review number: 128
Review: Tudo certinho
--------------------------------------------------------------------------------
Review number: 129
Review: faltou as duas peças do aparelho massageador
--------------------------------------------------------------------------------
Review number: 130
Review: sim

--------------------------------------------------------------------------------
Review number: 131
Review: Melhor preço e entrega super rápida, sou fregues a muito tempo, loja totalmente confiável...
--------------------------------------------------------------------------------
Review number: 132
Review: Produto veio certinho e no prazo!!
--------------------------------------------------------------------------------
Review number: 133
Review: Seria uma sugestão, as imagens não são parecidas com o produto original, se possivel tirar fotos do produto de uma forma que a visualização seja mais clara.
Pois o produto que comprei achei diferente
--------------------------------------------------------------------------------
Review number: 134
Review: Comprei duas válvulas solenóides iguais. Paguei o mesmo produto com quantidade 2 (dois). As válvulas são iguais, mas as roscas são diferentes. Uma é BSP, com passo igual a NPT, a outra tem passo maio
--------------------------------------------------------------------------------
Review number: 135
Review: O produto solicitado foi entregue com algum atraso mas em perfeito estado,Muito Obrigado.
--------------------------------------------------------------------------------
Review number: 136
Review: embora tenha comprado o produto durante a Black Friday para presentear uma criança da família, o presente não chegou a tempo do Natal. Fui obrigada a comprar às pressas um presente substituto
--------------------------------------------------------------------------------
Review number: 137
Review: Produto muito bom, confortável,
--------------------------------------------------------------------------------
Review number: 138
Review: Entrega super rápida, Amei o produto, com certeza indico
--------------------------------------------------------------------------------
Review number: 139
Review: Muito bom,
--------------------------------------------------------------------------------
Review number: 140
Review: Produto recebido.dentro do prazo, características conforme anunciado.
--------------------------------------------------------------------------------

In [164]:
batch_7 = claude_input.iloc[140:180][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_7.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 141
Review: O relógio tem uma boa qualidade.
--------------------------------------------------------------------------------
Review number: 142
Review: Muito satisfeita, produto chegou antes do prazo em perfeita condições , parabéns nota 10
--------------------------------------------------------------------------------
Review number: 143
Review: Produto chegou antes do prazo
--------------------------------------------------------------------------------
Review number: 144
Review: Entregou o produto de forma correta e antes do prazo, muito eficiente.
--------------------------------------------------------------------------------
Review number: 145
Review: até o momento não recebi meu produto
--------------------------------------------------------------------------------
Review number: 146
Review: Além do prazo de entrega ser super demorado, agora não consigo contacta-los pra saber o que está acontecendo e quando ou se vão entregar.
--------------------------------------------------------------------------------
Review number: 147
Review: Comprei e não levei, comprei em novembro com promessa de receber o produto em 12 dias, ja se passaram mais de 30 dias... e o pior
SEM NENHUM CONTATO, sem nenhuma informação. detalhe 2 parcelas pagas
--------------------------------------------------------------------------------
Review number: 148
Review: e uma loja muito boa

--------------------------------------------------------------------------------
Review number: 149
Review: Infelizmente o produto não possui boa qualidade e fica permanentemente com a luz ligada, tendo alto consumo de energia (pilhas)
--------------------------------------------------------------------------------
Review number: 150
Review: òtimo serviço
--------------------------------------------------------------------------------
Review number: 151
Review: Chegou antes do prazo
--------------------------------------------------------------------------------
Review number: 152
Review: Os produtos chegaram direitinho e antes do prazo!!! Excelente!!
--------------------------------------------------------------------------------
Review number: 153
Review: Muito bom
--------------------------------------------------------------------------------
Review number: 154
Review: O produto chegou rápido e em perfeito estado.

--------------------------------------------------------------------------------
Review number: 155
Review: Chegou antes do prazo , super recomendo
--------------------------------------------------------------------------------
Review number: 156
Review: Boa empresa entregou antes doi prazo. Produto em perfeito estado.
--------------------------------------------------------------------------------
Review number: 157
Review: produto lindo, qualidade e preço excelentes.
Entrega antes do prazo previsto.
--------------------------------------------------------------------------------
Review number: 158
Review: entregaram no prazo e produto correto
--------------------------------------------------------------------------------
Review number: 159
Review: Produto diferente do que foi anunciado.
--------------------------------------------------------------------------------
Review number: 160
Review: Chegou muito rápido.
--------------------------------------------------------------------------------
Review number: 161
Review: Super enrolado.. transporte desatualizado, e fora do prazo. Mais de 30 dias esperando .
--------------------------------------------------------------------------------
Review number: 162
Review: Produto bom, forte e bom acabamento
--------------------------------------------------------------------------------
Review number: 163
Review: Produto foi entregue muito antes do prazo determinado.
--------------------------------------------------------------------------------
Review number: 164
Review: Voltaria a comprar
--------------------------------------------------------------------------------
Review number: 165
Review: O PRODUTO O QUAL CHEGOU EM MINHA RESIDENCIA , ERA SIM O PRODUTO O QUAL EU HAVIA FEITO O PEDIDO, POREM O PRODUTO NAO ESTAVA NOS PADROES O QUAL DEVERIA SE ENCONTRAR , FOI UMA FALTA TOTAL DE RESPEITO .
--------------------------------------------------------------------------------
Review number: 166
Review: Só não coerente o valor do frete.
--------------------------------------------------------------------------------
Review number: 167
Review: Eu recomendo a empresa
--------------------------------------------------------------------------------
Review number: 168
Review: Muito bom essa loja !!
Parabéns!
--------------------------------------------------------------------------------
Review number: 169
Review: Mesmo com a paralisação o produto chegou antes do previsto. E vieram sem nenhum problema
--------------------------------------------------------------------------------
Review number: 170
Review: amei o produto ja estou usando
--------------------------------------------------------------------------------
Review number: 171
Review: eu amei meu pedicuro mais gostaria de saber a respeito da nota da garantia estendida
--------------------------------------------------------------------------------
Review number: 172
Review: Produto com etiqueta de autenticidade.
--------------------------------------------------------------------------------
Review number: 173
Review: Tudo certo com a garantia estendida, também.
--------------------------------------------------------------------------------
Review number: 174
Review: chegou antes do prazo
--------------------------------------------------------------------------------
Review number: 175
Review: O jogo de panelas e lindo e muito bom. So uma das frigideiras que soltou uns pontinhos de tinta. Mas o resto perfeito
--------------------------------------------------------------------------------
Review number: 176
Review: Embora eu ter recebido o produto em dias, mas o meu produto veio com avaria o produto foi uma película de um smartphone da Asus zenfone 3 zoom a película veio trincada...
--------------------------------------------------------------------------------
Review number: 177
Review: Quero o produto que comprei. Paguei pelo amarelo e pelo acgua 2 produtos diferentes pela cor.
Me enviaram 2 Acqua
--------------------------------------------------------------------------------
Review number: 178
Review: entrega foi rapida
--------------------------------------------------------------------------------
Review number: 179
Review: Satisfeita com a compra. Entrega rápida , super indico essa loja.
--------------------------------------------------------------------------------
Review number: 180
Review: Produto maravilhoso, recebi antes do prazo. Tudo muito bem embalado.
--------------------------------------------------------------------------------

In [165]:
batch_8 = claude_input.iloc[180:200][
    ['review_number', 'order_id', 'review_comment_message']
].copy()

for _, row in batch_8.iterrows():
    print(f"Review number: {row['review_number']}")
    print(f"Review: {row['review_comment_message']}")
    print("-" * 80)

Review number: 181
Review: Recebí dentro do prazo!
Kit original!
--------------------------------------------------------------------------------
Review number: 182
Review: A entrega foi muito rápida e o produto atende as expectativas!
--------------------------------------------------------------------------------
Review number: 183
Review: Produto de ótima qualidade e entrega dentro do prazo
--------------------------------------------------------------------------------
Review number: 184
Review: Muito bom mesmo chegou com 7 dias
--------------------------------------------------------------------------------
Review number: 185
Review: São muito atenciosos e prestativos.

--------------------------------------------------------------------------------
Review number: 186
Review: É muito difícil o contato com vocês pois às vezes o problema não se enquadra nas opções disponíveis no site.
--------------------------------------------------------------------------------
Review number: 187
Review: Não foi entegue
--------------------------------------------------------------------------------
Review number: 188
Review: Consta no site que o meu pedido já foi entregue porém não recebi favor verificar os dados da pessoa que recebeu e me retornar com urgência pois vou atrás do meu direito como consumidor.aguardo retorno
--------------------------------------------------------------------------------
Review number: 189
Review: Ótima compra. Obrigado.
--------------------------------------------------------------------------------
Review number: 190
Review: Muito bom o produto
--------------------------------------------------------------------------------
Review number: 191
Review: Entrega dentro do prazo estabelecido. Produto em ótimas condições.Produto em si excelente!
--------------------------------------------------------------------------------
Review number: 192
Review: comprei 2 unidades recebi 1 unidade
ainda paguei 2 fretes para vir junto
--------------------------------------------------------------------------------
Review number: 193
Review: Ainda não recebi meu produto, esta totalmente fora do prazo de entrega, me sinto lesado
--------------------------------------------------------------------------------
Review number: 194
Review: O produto é bom e a entrega foi rápida
--------------------------------------------------------------------------------
Review number: 195
Review: Produto de qualidade.
--------------------------------------------------------------------------------
Review number: 196
Review: Comprei um item limpador de ar condicionado automotivo de lima limão, enviaram de lavanda.

De qualquer forma chegou o produto.
--------------------------------------------------------------------------------
Review number: 197
Review: Entregou bem antes do prazo.
--------------------------------------------------------------------------------
Review number: 198
Review: O prazo para entrega era dia 14/05 e até agora não chegou. Uma falta de respeito com o consumidor. O numero do pedido nem sequer aparece na relação de pedidos no site lannister.com
--------------------------------------------------------------------------------
Review number: 199
Review: super recomendo
--------------------------------------------------------------------------------
Review number: 200
Review: Previsão de entrega até 18/10, recebi em 05/10, excelente.
--------------------------------------------------------------------------------

In [166]:
ai_results = pd.DataFrame({
    'review_number': list(range(1, 201)),
    'theme': [
        # 1–20
        'product_quality', 'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'good_experience', 'wrong_or_missing_item',
        'late_or_not_received', 'product_quality', 'good_experience',
        'other', 'late_or_not_received', 'late_or_not_received', 'good_experience',
        'late_or_not_received', 'late_or_not_received', 'late_or_not_received',
        'wrong_or_missing_item', 'product_quality', 'other',

        # 21–40
        'product_quality', 'product_quality', 'good_experience',
        'wrong_or_missing_item', 'good_experience', 'good_experience',
        'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'wrong_or_missing_item', 'good_experience',
        'wrong_or_missing_item', 'product_quality', 'wrong_or_missing_item',
        'wrong_or_missing_item', 'good_experience', 'other',
        'good_experience', 'good_experience',

        # 41–60
        'good_experience', 'late_or_not_received', 'other',
        'wrong_or_missing_item', 'good_experience', 'late_or_not_received',
        'product_quality', 'good_experience', 'product_quality',
        'good_experience', 'product_quality', 'good_experience', 'other',
        'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'product_quality', 'good_experience',
        'late_or_not_received',

        # 61–80
        'good_experience', 'product_quality', 'good_experience',
        'product_quality', 'late_or_not_received', 'good_experience',
        'good_experience', 'late_or_not_received', 'good_experience',
        'good_experience', 'good_experience', 'product_quality',
        'good_experience', 'good_experience', 'product_quality',
        'good_experience', 'good_experience', 'good_experience',
        'product_quality', 'late_or_not_received',

        # 81–100
        'good_experience', 'wrong_or_missing_item', 'good_experience',
        'good_experience', 'wrong_or_missing_item', 'good_experience',
        'good_experience', 'late_or_not_received', 'late_or_not_received',
        'good_experience', 'good_experience', 'wrong_or_missing_item',
        'wrong_or_missing_item', 'other', 'good_experience',
        'wrong_or_missing_item', 'good_experience', 'good_experience',
        'good_experience', 'good_experience',

        # 101–120
        'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'late_or_not_received', 'good_experience',
        'good_experience', 'late_or_not_received', 'good_experience',
        'good_experience', 'good_experience', 'product_quality', 'other',
        'product_quality', 'late_or_not_received', 'good_experience',
        'good_experience', 'good_experience', 'late_or_not_received',
        'product_quality',

        # 121–140
        'good_experience', 'wrong_or_missing_item', 'good_experience',
        'good_experience', 'good_experience', 'good_experience',
        'wrong_or_missing_item', 'good_experience', 'wrong_or_missing_item',
        'other', 'good_experience', 'good_experience', 'product_quality',
        'product_quality', 'late_or_not_received', 'late_or_not_received',
        'good_experience', 'good_experience', 'good_experience',
        'good_experience',

        # 141–160
        'product_quality', 'good_experience', 'good_experience',
        'good_experience', 'late_or_not_received', 'late_or_not_received',
        'late_or_not_received', 'good_experience', 'good_experience',
        'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'good_experience', 'good_experience',
        'wrong_or_missing_item', 'good_experience',

        # 161–180
        'late_or_not_received', 'product_quality', 'good_experience',
        'good_experience', 'product_quality', 'other', 'good_experience',
        'good_experience', 'good_experience', 'good_experience', 'other',
        'product_quality', 'good_experience', 'good_experience',
        'product_quality', 'product_quality', 'wrong_or_missing_item',
        'good_experience', 'good_experience', 'good_experience',

        # 181–200
        'good_experience', 'good_experience', 'good_experience',
        'good_experience', 'good_experience', 'other',
        'late_or_not_received', 'late_or_not_received', 'good_experience',
        'good_experience', 'good_experience', 'wrong_or_missing_item',
        'late_or_not_received', 'good_experience', 'product_quality',
        'wrong_or_missing_item', 'good_experience', 'late_or_not_received',
        'good_experience', 'good_experience'
    ]
})

ai_results.shape

(200, 2)

In [167]:
ai_results = ai_results.merge(
    claude_input[['review_number', 'delivery_status']],
    on='review_number',
    how='left'
)

ai_results.head()

   review_number            theme delivery_status
0              1  product_quality         On-Time
1              2  good_experience         On-Time
2              3  good_experience         On-Time
3              4  good_experience         On-Time
4              5  good_experience         On-Time

In [170]:
summaries = [
    "Wallet is well finished and made of leather as specified.",
    "The product was good and delivered on time.",
    "The delivery was fast.",
    "The order arrived on time and met expectations.",
    "The order was delivered ahead of schedule and the customer was satisfied.",
    "The order arrived correctly within the agreed time.",
    "Three curtains were missing from the order.",
    "The delivery took too long but arrived in perfect condition.",
    "The product met expectations and had no defects.",
    "The order arrived on time.",
    "The review is too short to determine the experience.",
    "The product was good but the delivery was disappointing.",
    "The customer did not receive the product.",
    "The customer had a positive experience.",
    "The customer wants faster deliveries.",
    "The customer wants a quick refund or is still waiting for delivery.",
    "The promised delivery time was not met.",
    "A connector was missing from the order.",
    "The product lacked a manual and required Windows.",
    "The review is too short to determine the experience.",

    "The curtain fabric was extremely thin and the customer wants an exchange.",
    "The lids arrived broken due to inadequate packaging.",
    "The customer loved the backpack, which arrived on the child's birthday.",
    "The cushions did not arrive.",
    "The customer gave a positive review.",
    "Everything was fine with the delivery.",
    "The products were good quality and delivered before the deadline.",
    "The customer described the experience positively.",
    "The order arrived early and the product was being tested.",
    "The customer liked the purchase and its good quality.",
    "The customer ordered 240 tablets but received only 120.",
    "The delivery was very fast.",
    "The customer ordered three wine bottles but received two.",
    "The product was damaged after being connected to 220V instead of 110V.",
    "The delivered charger had half the advertised amperage.",
    "The customer received only one of two pieces.",
    "The delivery was very fast although the product had not been installed yet.",
    "The cartridge requirement was not clearly stated.",
    "The product was excellent and arrived in good condition.",
    "The product was good and arrived very quickly.",

    "The purchase was great for a limited space.",
    "The transformer was not received and carrier follow-up was delayed.",
    "The order was canceled and the customer asks how to reorder using the paid amount.",
    "The wrong color was shipped.",
    "The customer described the product positively.",
    "The delivery took longer than other orders.",
    "The product quality was poor and the material was too thin.",
    "The customer had an excellent experience and recommends the product.",
    "The material and finish quality were worse than expected from the website.",
    "The product was excellent for a photographer.",
    "The product was close to its expiration date and the customer wants an exchange.",
    "The customer liked the service.",
    "The customer found the shipping cost too expensive.",
    "The order arrived correctly, early, well packaged, and undamaged.",
    "The product was good quality and matched the image.",
    "The customer had an excellent experience and regularly buys here.",
    "The store was reliable, fast, and offered a good price.",
    "The customer believed the watch was counterfeit and poor quality.",
    "The order arrived early and had excellent quality.",
    "The customer did not receive the order.",

    "The order fulfilled what was agreed.",
    "The screen protector was scratched and had insufficient adhesive.",
    "The magnesium chloride kit offered better value than buying separately.",
    "The battery charger had a small manufacturing defect.",
    "The delivery took longer than competitors but arrived before the deadline.",
    "The customer described the experience positively.",
    "The customer recommends the store for quality, price, and speed.",
    "The customer experienced a delivery problem or delay.",
    "The product was excellent.",
    "The child loved the beautiful product, which arrived on time and intact.",
    "The customer intends to continue buying from the store.",
    "Poor packaging caused the product to need repairs.",
    "The customer described the service as excellent.",
    "The delivery was fine and the product was very good.",
    "The box was partly open and the warranty or expiration date was close.",
    "Everything was fine with the order.",
    "The merchandise was perfect and the customer recommends it.",
    "The customer liked the product.",
    "The supposedly branded Targus product appeared to be counterfeit.",
    "The customer did not receive the order.",

    "The product exceeded expectations, arrived early, and had good quality.",
    "The packaging was labeled for a different Honda model.",
    "The order arrived on time and the product was good and easy to apply.",
    "The order arrived early and the frame was exactly as desired.",
    "Two kitchen mat products were missing.",
    "The customer described the product as excellent.",
    "The product was original, reasonably priced, and delivered quickly.",
    "The customer received no updates about the order.",
    "The customer did not receive the belt.",
    "The customer received the correct order.",
    "The product was excellent and delivery was fast.",
    "The customer ordered gold and white brushes but received pink ones.",
    "The customer ordered a transparent phone case but received a colorful one.",
    "The customer questioned why the order had to be collected at the post office despite paying for delivery.",
    "The customer described the product as excellent.",
    "The customer received a different vacuum model.",
    "The customer described the product as excellent.",
    "The order arrived on time and was well packaged.",
    "The watch was excellent and as described.",
    "The customer described the experience positively.",

    "The platform was excellent for shopping.",
    "The customer praised the delivery.",
    "The product was exactly as expected and perfect.",
    "The customer had a very good shopping experience.",
    "The product was not delivered and the customer received no response.",
    "The product arrived early, well packaged, and beautiful.",
    "The customer considered the product excellent.",
    "The customer had to collect the order from the post office despite paying for home delivery.",
    "The customer praised the product's excellent quality.",
    "The customer described the experience as good.",
    "The product arrived early and was of great quality.",
    "The customer was uncertain whether the hard plastic product could withstand the lamp's heat.",
    "The customer experienced an incorrect price but the issue was resolved.",
    "The customer considered the product to be poor quality.",
    "The customer found the delivery slower than other products.",
    "The customer praised the product and fast delivery.",
    "The product matched the advertised quality and arrived early.",
    "The customer praised the excellent and very fast delivery.",
    "The customer complained repeatedly about delivery without receiving a response.",
    "The customer felt the product's finish could be improved.",

    "The product exceeded the customer's expectations.",
    "The customer paid for a complete kit but received only the curl activator.",
    "The product arrived early, was correctly described, and was well packaged.",
    "Everything was as expected and arrived on time.",
    "The customer considered the store very good.",
    "The customer praised the very fast delivery.",
    "The customer received a different product from the one ordered.",
    "Everything was correct with the order.",
    "Two pieces of the massage device were missing.",
    "The review is too unclear to determine a specific issue.",
    "The customer praised the price, fast delivery, and reliability of the store.",
    "The product arrived correctly and on time.",
    "The product differed from its images and the customer suggested clearer product photos.",
    "The two identical valves had different thread specifications.",
    "The product arrived late but was received in perfect condition.",
    "The delivery arrived too late for Christmas, requiring a replacement gift.",
    "The customer considered the product very good and comfortable.",
    "The customer praised the fast delivery and loved the product.",
    "The customer considered the experience very good.",
    "The product arrived on time and matched the advertised characteristics.",

    "The watch was considered good quality.",
    "The product arrived early and in perfect condition.",
    "The product arrived ahead of schedule.",
    "The correct product was delivered ahead of schedule.",
    "The customer had not received the product yet.",
    "The delivery was very delayed and the customer could not get information about it.",
    "The product was over 30 days late with no delivery information or contact.",
    "The customer considered the store very good.",
    "The product had poor quality and stayed permanently lit, consuming too many batteries.",
    "The customer considered the service excellent.",
    "The product arrived ahead of schedule.",
    "The products arrived correctly and ahead of schedule.",
    "The customer considered the product very good.",
    "The product arrived quickly and in perfect condition.",
    "The product arrived ahead of schedule and was highly recommended.",
    "The company delivered ahead of schedule and the product was in perfect condition.",
    "The product was beautiful and arrived ahead of schedule.",
    "The correct product was delivered on time.",
    "The product was different from what was advertised.",
    "The product arrived very quickly.",

    "The delivery was over 30 days late with outdated transport information.",
    "The product was strong and had good finishing.",
    "The product was delivered well before the expected date.",
    "The customer would buy from the store again.",
    "The correct product arrived but was not in the expected condition.",
    "The customer considered the shipping cost unreasonable.",
    "The customer recommends the company.",
    "The customer was very satisfied with the store.",
    "The product arrived earlier than expected without any problems.",
    "The customer loved the product and was already using it.",
    "The customer wanted information about the extended warranty document.",
    "The product had an authenticity label.",
    "Everything was correct with the extended warranty.",
    "The product arrived ahead of schedule.",
    "The cookware set was good, but one frying pan had areas where the paint came off.",
    "The product arrived quickly but the smartphone screen protector was cracked.",
    "The customer ordered two different colors but received two items in the same color.",
    "The delivery was fast.",
    "The customer was satisfied with the purchase and praised the fast delivery.",
    "The product was wonderful, arrived early, and was well packaged.",

    "The order arrived on time and was an original kit.",
    "The delivery was very fast and the product met expectations.",
    "The product was high quality and arrived on time.",
    "The product arrived in seven days and the customer was very satisfied.",
    "The customer found the service attentive and helpful.",
    "The customer found it difficult to contact support because some issues did not fit the website options.",
    "The order was not delivered.",
    "The order was marked as delivered but the customer did not receive it.",
    "The customer was very satisfied with the purchase.",
    "The customer liked the product.",
    "The order arrived on time and the product was in excellent condition and quality.",
    "The customer ordered two units but received only one.",
    "The customer had not received the product and the delivery was far past the expected deadline.",
    "The product was good and the delivery was fast.",
    "The customer praised the product quality.",
    "The customer ordered lemon-scented cleaner but received lavender-scented cleaner.",
    "The order was delivered well ahead of schedule.",
    "The order was not delivered by the promised date.",
    "The customer highly recommends the product.",
    "The order arrived well before the expected delivery date."
]

len(summaries)

200

In [168]:
theme_mix = pd.crosstab(
    ai_results['delivery_status'],
    ai_results['theme']
)

theme_mix

theme,good_experience,late_or_not_received,other,product_quality,wrong_or_missing_item
delivery_status,,,,,
Late,1,18,0,0,2
On-Time,113,10,11,27,18

In [169]:
theme_mix_percent = pd.crosstab(
    ai_results['delivery_status'],
    ai_results['theme'],
    normalize='index'
) * 100

theme_mix_percent.round(1)

theme,good_experience,late_or_not_received,other,product_quality,wrong_or_missing_item
delivery_status,,,,,
Late,4.8,85.7,0.0,0.0,9.5
On-Time,63.1,5.6,6.1,15.1,10.1

In [171]:
ai_results = ai_results.merge(
    claude_input[['review_number', 'delivery_status']],
    on='review_number',
    how='left'
)

ai_results.head()

   review_number            theme delivery_status_x delivery_status_y
0              1  product_quality           On-Time           On-Time
1              2  good_experience           On-Time           On-Time
2              3  good_experience           On-Time           On-Time
3              4  good_experience           On-Time           On-Time
4              5  good_experience           On-Time           On-Time

In [172]:
len(summaries)

200

In [173]:
ai_results['summary'] = summaries

ai_results.head()

,review_number,theme,delivery_status_x,delivery_status_y,summary
0,1,product_quality,On-Time,On-Time,Wallet is well finished and made of leather as...
1,2,good_experience,On-Time,On-Time,The product was good and delivered on time.
2,3,good_experience,On-Time,On-Time,The delivery was fast.
3,4,good_experience,On-Time,On-Time,The order arrived on time and met expectations.
4,5,good_experience,On-Time,On-Time,The order was delivered ahead of schedule and ...

In [174]:
ai_results = ai_results.drop(columns=['delivery_status_x'])

ai_results = ai_results.rename(
    columns={'delivery_status_y': 'delivery_status'}
)

ai_results.head()

,review_number,theme,delivery_status,summary
0,1,product_quality,On-Time,Wallet is well finished and made of leather as...
1,2,good_experience,On-Time,The product was good and delivered on time.
2,3,good_experience,On-Time,The delivery was fast.
3,4,good_experience,On-Time,The order arrived on time and met expectations.
4,5,good_experience,On-Time,The order was delivered ahead of schedule and ...

In [175]:
print("Rows:", len(ai_results))
print("Unique review numbers:", ai_results['review_number'].nunique())
print("Missing themes:", ai_results['theme'].isna().sum())
print("Missing delivery status:", ai_results['delivery_status'].isna().sum())
print("Missing summaries:", ai_results['summary'].isna().sum())

Rows: 200
Unique review numbers: 200
Missing themes: 0
Missing delivery status: 0
Missing summaries: 0

In [176]:
ai_results.to_csv(
    "part_c_ai_results.csv",
    index=False
)

print("Saved: part_c_ai_results.csv")

Saved: part_c_ai_results.csv

In [177]:
prompt = """You are classifying customer reviews for an e-commerce delivery analysis.

For EACH review, return exactly:
Review number:
Theme:
Summary:

Choose exactly ONE theme from these five:
1. late_or_not_received
2. wrong_or_missing_item
3. product_quality
4. good_experience
5. other

Rules:
- If a review mentions several issues, choose the single most important theme based on the customer's main complaint.
- Delivery delay, not received, lost delivery, or delivery taking too long → late_or_not_received.
- Wrong item, missing item, missing parts, or incomplete order → wrong_or_missing_item.
- Defective, damaged, broken, poor-quality, or product-related problems → product_quality.
- Clearly positive experience with no major complaint → good_experience.
- Unclear, extremely short, unrelated, refund/payment/support issues that do not fit the other categories → other.
- Reviews may be in Portuguese. Understand the Portuguese text, but write the Summary in English.
- Keep the Summary to ONE short sentence.
- Do not add explanations or extra categories.

Here are the reviews:
[PASTE BATCH HERE]
"""

with open("part_c_ai_prompt.txt", "w", encoding="utf-8") as f:
    f.write(prompt)

print("Saved: part_c_ai_prompt.txt")

Saved: part_c_ai_prompt.txt

In [178]:
validation_30.to_csv(
    "part_c_manual_validation_30.csv",
    index=False
)

print("Saved: part_c_manual_validation_30.csv")

Saved: part_c_manual_validation_30.csv

In [180]:
os.listdir("Dataset")

['.ipynb_checkpoints',
 'olist_orders_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_sellers_dataset.csv']

In [181]:
sellers=pd.read_csv('Dataset/olist_sellers_dataset.csv')

In [182]:
sellers.shape

(3095, 4)

In [183]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [184]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [185]:
seller_orders = order_items[['order_id', 'seller_id']].drop_duplicates()

seller_order_count = (
    seller_orders
    .groupby('seller_id')
    .size()
    .reset_index(name='order_count')
)

seller_order_count.head()

                          seller_id  order_count
0  0015a82c2db000af6aaaf3ae2ecb0532            3
1  001cca7ae9ae17fb1caed9dfb1094831          200
2  001e6ad469a905060d959994f1b41e4f            1
3  002100f778ceb8431b7a1020ff7ab48f           51
4  003554e2dce176b5555353e4f3555ac8            1

In [186]:
eligible_sellers = seller_order_count[
    seller_order_count['order_count'] >= 50
].copy()

print("Eligible sellers:", len(eligible_sellers))
eligible_sellers.head()

Eligible sellers: 429

                           seller_id  order_count
1   001cca7ae9ae17fb1caed9dfb1094831          200
3   002100f778ceb8431b7a1020ff7ab48f           51
5   004c9cd9d87a3c30c522c48c4fc07416          158
9   00ee68308b45bc5e2660cd833c3f81cc          135
10  00fc707aaaad2d31347cf883cd2dfe10          103

In [187]:
delivered_order_sellers = (
    order_items[['order_id', 'seller_id']]
    .drop_duplicates()
    .merge(
        delivered_orders[['order_id', 'days_late']],
        on='order_id',
        how='inner'
    )
)

delivered_order_sellers.head()

,order_id,seller_id,days_late
0,00010242fe8c5a6d1ba2dd792cb16214,48436dade18ac8b2bce089ec2a041202,0.0
1,00018f77f2f0320c557190d7a144bdd3,dd7ddc04e1b6c2c614352b383efe2d36,0.0
2,000229ec398224ef6ca0657da4fc703e,5b51032eddd242adc84c38acab88f23d,0.0
3,00024acbcdf0a6daa1e931b038114c75,9d7a1d34a5052409006425275ba1c2b4,0.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,df560393f3a51e74553ab94004ba5c87,0.0

In [188]:
seller_late_share = (
    delivered_order_sellers
    .groupby('seller_id')
    .agg(
        delivered_orders=('order_id', 'nunique'),
        late_orders=('days_late', lambda x: (x > 0).sum())
    )
    .reset_index()
)

seller_late_share['late_share'] = (
    seller_late_share['late_orders']
    / seller_late_share['delivered_orders']
)

seller_late_share.head()

                          seller_id  delivered_orders  late_orders  late_share
0  0015a82c2db000af6aaaf3ae2ecb0532                 3            0    0.000000
1  001cca7ae9ae17fb1caed9dfb1094831               195           12    0.061538
2  002100f778ceb8431b7a1020ff7ab48f                50            9    0.180000
3  003554e2dce176b5555353e4f3555ac8                 1            0    0.000000
4  004c9cd9d87a3c30c522c48c4fc07416               156           10    0.064103

In [189]:
seller_final = eligible_sellers.merge(
    seller_late_share,
    on='seller_id',
    how='left'
)

seller_final.head()

,seller_id,order_count,delivered_orders,late_orders,late_share
0,001cca7ae9ae17fb1caed9dfb1094831,200,195,12,0.061538
1,002100f778ceb8431b7a1020ff7ab48f,51,50,9,0.180000
2,004c9cd9d87a3c30c522c48c4fc07416,158,156,10,0.064103
3,00ee68308b45bc5e2660cd833c3f81cc,135,135,10,0.074074
4,00fc707aaaad2d31347cf883cd2dfe10,103,103,4,0.038835

In [190]:
seller_final = seller_final.merge(
    sellers[['seller_id', 'seller_city', 'seller_state']],
    on='seller_id',
    how='left'
)

seller_final.head()

,seller_id,order_count,delivered_orders,late_orders,late_share,seller_city,seller_state
0,001cca7ae9ae17fb1caed9dfb1094831,200,195,12,0.061538,cariacica,ES
1,002100f778ceb8431b7a1020ff7ab48f,51,50,9,0.180000,franca,SP
2,004c9cd9d87a3c30c522c48c4fc07416,158,156,10,0.064103,ibitinga,SP
3,00ee68308b45bc5e2660cd833c3f81cc,135,135,10,0.074074,sao paulo,SP
4,00fc707aaaad2d31347cf883cd2dfe10,103,103,4,0.038835,maringa,PR

In [191]:
print("Number of sellers:", seller_final['seller_id'].nunique())
print("Minimum order count:", seller_final['order_count'].min())
print("Missing seller details:", seller_final['seller_city'].isna().sum())
print("Missing late share:", seller_final['late_share'].isna().sum())
print("Duplicate seller IDs:", seller_final['seller_id'].duplicated().sum())
print("Late share below 0:", (seller_final['late_share'] < 0).sum())
print("Late share above 1:", (seller_final['late_share'] > 1).sum())

Number of sellers: 429
Minimum order count: 50
Missing seller details: 0
Missing late share: 0
Duplicate seller IDs: 0
Late share below 0: 0
Late share above 1: 0

In [192]:
seller_final.to_csv(
    "seller_late_share.csv",
    index=False
)

print("Saved: seller_late_share.csv")

Saved: seller_late_share.csv

In [193]:
print("Orders:", len(orders))
print("Delivered orders:", len(delivered_orders))
print("Non-delivered orders:", len(orders) - len(delivered_orders))
print("Final delivered table:", len(delivered_orders))
print("Delivered orders without review:", delivered_orders['review_score'].isna().sum())
print("Delivered orders without item count:", delivered_orders['item_count'].isna().sum())
print("Delivered orders without order value:", delivered_orders['order_value'].isna().sum())

Orders: 99441
Delivered orders: 96478
Non-delivered orders: 2963
Final delivered table: 96478
Delivered orders without review: 646
Delivered orders without item count: 0
Delivered orders without order value: 0

In [194]:
top_late_sellers = seller_final.sort_values(
    'late_share',
    ascending=False
).head(10)

top_late_sellers[
    [
        'seller_id',
        'order_count',
        'delivered_orders',
        'late_orders',
        'late_share',
        'seller_city',
        'seller_state'
    ]
]

,seller_id,order_count,delivered_orders,late_orders,late_share,seller_city,seller_state
144,54965bbe3e4f07ae045b90b0b8541f52,78,73,22,0.301370,foz do iguacu,PR
82,2a1348e9addc1af5aaa619b1a3679d6b,52,48,13,0.270833,belo horizonte,MG
319,beadbee30901a7f61d031b6b686095ad,64,64,15,0.234375,guarulhos,SP
287,a49928bcdf77c55c6d6e05e09a9b4ca5,98,96,21,0.218750,sao paulo,SP
193,712e6ed8aa4aa1fa65dab41fed5737e4,79,77,16,0.207792,videira,SC
20,06a2c3af7b3aee5d69171b0e14f0ee87,392,389,74,0.190231,sao luis,MA
393,ea566164622c6b439516ab18062c42cd,50,50,9,0.180000,sao paulo,SP
1,002100f778ceb8431b7a1020ff7ab48f,51,50,9,0.180000,franca,SP
334,cac4c8e7b1ca6252d8f20b2fc1a2e4af,75,74,13,0.175676,indaiatuba,SP
161,6039e27294dc75811c0d8a39069f52c0,64,63,11,0.174603,osasco,SP

In [195]:
print("Orders:", len(orders))
print("Delivered orders:", len(delivered_orders))
print("Non-delivered orders:", len(orders) - len(delivered_orders))
print("Delivered orders without review:", delivered_orders['review_score'].isna().sum())
print("Delivered orders without item count:", delivered_orders['item_count'].isna().sum())
print("Delivered orders without order value:", delivered_orders['order_value'].isna().sum())

Orders: 99441
Delivered orders: 96478
Non-delivered orders: 2963
Delivered orders without review: 646
Delivered orders without item count: 0
Delivered orders without order value: 0